COS301-SE-2022/Team-Utilisation-Monitor

team-utilisation-monitor/libs/client/authentication/feature/src/lib/client-authentication-feature.module.ts, team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.html, team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.scss
Login Page integrated w/ Angular Material
- added top nav
- added login and register panel
- added login input boxes and login button
- lined the buttons to the router
(need to add)
- About Page at bottom of the page
=> Login Page integrated w/ Angular Material

team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.html, team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.scss
- Finalize Login Page with footer and final standings of the login and sign up forms
=> Finalize Login Page

team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.spec.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.spec.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.scss, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.spec.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/client-admin-feature.module.ts, team-utilisation-monitor/nx.json
Added the following components to the admin/feature lib:
- Admin Home Page
- Admin List View Page
- Admin Company View Page
=> Added Admin Page components

team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.scss, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.scss, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.scss
Added Multiple Documents:
- added HTML and CSS for Admin Home, Company and List view.
- updated SideNav to include navigation between pages
- added Card items for Admin Company View
- Added Remove Button to remove individuals from the company
=> Updated Admin Front End

node_modules/.yarn-integrity, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.scss, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/client-admin-feature.module.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-admin-topnav/comp-admin-topnav.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-admin-topnav/comp-admin-topnav.component.scss, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-admin-topnav/comp-admin-topnav.component.spec.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-admin-topnav/comp-admin-topnav.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.scss, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.spec.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.scss, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.spec.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-owner-individual/comp-owner-individual.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-owner-individual/comp-owner-individual.component.scss, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-owner-individual/comp-owner-individual.component.spec.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-owner-individual/comp-owner-individual.component.ts
Added two custom components to Admin Company View:
- Owner Individual
- Employee Individual
also added a data link between the parent and child.
Issue: We need to be able to generate multiples of the same component. meaning that the datalink needs to change in order for each employee to get their own name. currently all the components is linked to the same variable and will have the same name, Cornel does not yet know how to fix this issue
=> Front End of Admin Company View and NavBar component implementation

team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.scss, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.scss, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.scss
- added arrays for adding users
=> Finishing up Company View Front End

team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/client-admin-feature.module.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-list-view-individual/comp-list-view-individual.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-list-view-individual/comp-list-view-individual.component.scss, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-list-view-individual/comp-list-view-individual.component.spec.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-list-view-individual/comp-list-view-individual.component.ts
Preliminary view of Admin List View
- added List View Individual Component
- added array for adding users dynamically
- added custom utilization bar
=> Update Admin List View Front End

team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-user-popup/comp-add-user-popup.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-user-popup/comp-add-user-popup.component.scss, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.scss, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-team-popup/comp-create-team-popup.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-team-popup/comp-create-team-popup.component.scss
- Finalized Add user popup
- Finalized Create Team popup
- Finalized Create Project popup
=> Finalized Side Nav Popups

team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-routing.module.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.scss, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.spec.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/client-admin-feature.module.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-member-popup/comp-add-team-member-popup.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-member-popup/comp-add-team-member-popup.component.scss, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-member-popup/comp-add-team-member-popup.component.spec.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-member-popup/comp-add-team-member-popup.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.scss, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.spec.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.scss, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.spec.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.ts
- Added Team/Project View button to sideNav
- added Team/Project dropdown list in Team/Project component
- added html and css for all pages
- added backend linking to all components
- added popup to add team members
=> Added Team/Project View

team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.spec.ts
=> fixed failing tests

team-utilisation-monitor/libs/client/admin/feature/src/lib/client-admin-feature.module.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-data-view-popup/comp-project-data-view-popup.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-data-view-popup/comp-project-data-view-popup.component.scss, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-data-view-popup/comp-project-data-view-popup.component.spec.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-data-view-popup/comp-project-data-view-popup.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.scss, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.ts
- added popup to show teams in project with HTML/SCSS/TS integration
- added tooltips
- removed button for promoting/demoting admins
- changed project list to show hours per project and not teams
=> Popop to show teams in project

team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-list-view-individual/comp-list-view-individual.component.ts
- added over utalized bar case handling
- added fully utalized bar case handling
=> Bug fix: added more cases to List View bar chart

team-utilisation-monitor/libs/client/admin/feature/src/lib/client-admin-feature.module.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-member-popup/comp-add-team-member-popup.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-to-project-popup/comp-add-team-to-project-popup.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-user-popup/comp-add-user-popup.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-team-popup/comp-create-team-popup.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-individual/comp-team-individual.component.ts
- added snackbar popups for all Admin pages and operations currently in use.
- added timeout for all snackbars set at 5 seconds. i.e. snackbars disappear after 5 seconds
=> Added proper angular Popups for All admin Pages

team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.scss, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.scss, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.scss, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.scss, team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.scss
- added correct alignment
- added remove team button
- added left align to sidenav
=> Update Team/Project View on Admin Pages

team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts
added dropdown for Skills
fixed form controles
=> Front end modifications on the create Project popup

README.md, team-utilisation-monitor/.env, team-utilisation-monitor/Microservice-Authentication/.env, team-utilisation-monitor/apps/client-e2e/src/integration/app.spec.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.ts
Reverts COS301-SE-2022/Team-Utilisation-Monitor#632
=> Revert "update"

team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.ts
- In the admin company view, there was a syntax error due to the onResize function being above the constructor.
- I just moved it below the constructor on line 37
=> (Fix) admin company view was giving errors

team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.scss, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.ts
- I've fixed the assign hours feature. Now you can assign hours now.
- The solution was implemented using a FormArray(), not a regular Form.
- Ignore the redErrors at the console.
- This is because the FormArray is initially empty.
- But as it's being populated the errors will disappear.
- At the moment, it's working for employees. Not Admins.
=> (Fix) Fixed the assign hours.

team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.scss, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.ts, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.html, team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.scss
Active page button highlight
added a activeRouter Link to highlight the active page's button on the sidenav.
Removed Useless Code.
Expansion pannels open automatically if the "Expanded" property is given in the HTML. the boolean is thus redundant and not neccacary
Fixed top margin in Company View
Removing owner created a margin issue in Company View. it was due to this CSS.
=> Front end UI Updates

team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.ts
- The delete team is working on the frontend.
=> (FrontEnd) Remove team is working on ngxs

team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts, team-utilisation-monitor/prisma/seed.ts
Fix Applied to team project view
- Essentially, when you add a project, the state management would stall because it was being called in a recursive funcion.
- This fix fixes that.
=> 🐛 (Fix)Team/project view addProject
